### ISSUE TITLE
打不开？

### ISSUE THREAD

**Issue by ajian2002** [UserUnknownX/UserUnknownX.github.io#1]
真的打不开，来自https://ajian.online

**Comment by UserUnknownX** [comment]
> 真的打不开，来自https://ajian.online

我也不知道为什么...最近换hexo，发现一关电脑就白屏qwq我实在不行就今晚改回以前的备份吧qaq

**Comment by UserUnknownX** [comment]
> 真的打不开，来自https://ajian.online

好了哈，本人不太会友链配置，可能会晚点加QwQ

**Comment by UserUnknownX** [comment]
已经添加完毕(把hexo整崩了
